### ISSUE TITLE
No module found error

### ISSUE THREAD

**Issue by GURPREET-WEB** [youpengl/FedCHAR#1]
Dear friend,

Thanks for sharing your Work. 
Could you please resolve the following error shown in the screenshot? 
Also, please let me know whether I need to install the IMU dataset separately and, if so, where to place it in the GitHub code. 
![query](https://user-images.githubusercontent.com/69705267/236811502-0be5420a-4c26-4e96-bdeb-6304d32ae4f7.PNG)
Thanks.

**Comment by youpengl** [comment]
Thank you very much for your interest in our work. We have submitted the latest version with changes that will work. The specific modifications are [here](https://github.com/youpengl/FedCHAR/commit/c6af090ab49764973d14639e1bc9812858945341). In addition, we provide the IMU dataset (in json format) in the data/IMU directory for authors to run the code successfully only. You can also create custom datasets.

**Comment by GURPREET-WEB** [comment]
Thanks, friend. It's working now

**Comment by GURPREET-WEB** [comment]
Hi Youpengl,

I've been attempting to create the JSON file from the dataset, as you made
for the IMU train and test dataset, but I haven't been able to figure it
out.
If you have a Python file for that could you please share it, I would
greatly appreciate it.
Thank you for your time and help.

Best regards,
Gurpreet

**Comment by youpengl** [comment]
This is the example provided, but it will require further modify on your part. I hope this helps you. @GURPREET-WEB 
```
import numpy as np
import matplotlib.pyplot as plt

edgecolor = ['#000000', '#000000', '#000000', '#000000', '#000000', '#000000', '#000000', '#000000', '#000000', '#000000']
color = ['#A6CEE3', '#B2DF8A', '#FB9A99', '#FDBF6F', '#CAB2D6', '#FF7F00', '#FFF68F', '#1f77b4', '#ff7f0e', '#2ca02c']
hatch = ['---', '///', '\\\\\\', 'xxx', '|||', '...', '<<<', '~~~', '===', None]

def plot_distribution(client_labels, num_classes, num_clients, class_set, dataset):
    num_samples = np.array([label.shape[0] for label in client_labels])
    num_samples_index = np.argsort(-num_samples)
    arr = np.zeros([num_clients, num_classes])
    for idx, user_id in enumerate(num_samples_index):
        for class_id in range(num_classes):
            arr[idx][class_id] = client_labels[user_id].tolist().count(class_id)

    arr = arr.T
    x = ['Client {}'.format(i) for i in num_samples_index]
    fig = plt.figure(figsize=(10, 5))

    temp = np.zeros(shape=arr[0].shape)
    for class_idx in range(num_classes):
        if class_idx == 0:
            plt.bar(x, arr[class_idx], color=color[class_idx], hatch=hatch[class_idx], alpha=0.99, edgecolor=edgecolor[class_idx], label=class_set[class_idx])

        else:
            plt.bar(x, arr[class_idx], bottom=temp, color=color[class_idx], hatch=hatch[class_idx], alpha=0.99, edgecolor=edgecolor[class_idx], label=class_set[class_idx])
        temp += arr[class_idx]
    
    plt.legend(loc='upper right', fontsize=18)
    plt.gca().axes.xaxis.set_ticks([])
    plt.xlabel('User ID', fontsize=20)
    plt.ylabel('Num of Samples', fontsize=20)
    plt.title('{}'.format(dataset), fontsize=20)
    plt.tick_params(labelsize=20)
    fig.tight_layout()
    # plt.show()
    plt.savefig('dataset/{}/{}.pdf'.format(str.lower(dataset), dataset), bbox_inches='tight', pad_inches=0.0)
```

**Comment by GURPREET-WEB** [comment]
Thanks for sharing an example to create a JSON file of the custom dataset.
However, I didn't get any inferences from it as this is the code to plot a
bar plot.
Could you please share that Python file where you convert your IMU data to
JSON format? It would be very helpful.
Thanks.

**Comment by GURPREET-WEB** [comment]
[image: image.png]
I was asking about this train_data_dir and test_data_dir, which should be
in JSON format as mentioned in the arguments.
Thanks.
